### ISSUE TITLE
$trusted_ip not set in client-disconnect script if it were connected from ipv6

### ISSUE THREAD

**Issue by yangzhe1990** [jjo/openvpn-ipv6-legacy21#10]
as in title.

**Comment by jjo** [comment]
Hi,
It should be there as $trusted_ip6, I had decided to pass it as a different envvar name to ease scripting.
Would you please confirm me that you get $trusted_ip6 correctly set ?

Cheers,

**Comment by jjo** [comment]
FYI I committed the corresp manpage update at  7bdaa9c46e315241f8d19736dea3d77c98bf704e.

**Comment by yangzhe1990** [comment]
Yes, it works. Thank you.

**Comment by jjo** [comment]
Cool, thanks for the prompt feedback.
