### ISSUE TITLE
push "redirect-gateway def1" doesn't work using proto udp6

### ISSUE THREAD

**Issue by yegle** [jjo/openvpn-ipv6-legacy21#8]
Hi there, seems push "redirect-gateway def1" doesn't work here on my client.
Server and client both uses your patch:openvpn-2.1_rc20-ipv6-0.4.9.patch.gz

message in client log:
Thu Oct 29 11:40:48 2009 NOTE: unable to redirect default gateway -- Cannot obtain current remote host address

**Comment by jjo** [comment]
Indeed the patch doesn't add any ip6 routing cmds/etc (only ipv6 at "socket" level - ie: endpoints).
My idea is to start this sometime in the future but, because it's a whole can of worms itself, only I see some traction for the patch (not to mention some love for getting the patch in stock).

**Comment by jjo** [comment]
Hey yegle,
Can you clarify if you are seeing this bug for ipv6 and/or endpoint config(s) ?
Thanks!

**Comment by yegle** [comment]
Hi jjo,
I think this is related to the patch since I run two openvpn daemons (udp and upd6) on server, and the upd6 proto daemon doesn't change the default gateway automatically while the udp proto daemon does.
Tested on the same client with almost the same configure file.

**Comment by jjo** [comment]
yikes ... I whacked the wording of my previous question.

So, these are the two possible scenarios:

#1 patched for ipv6, --proto udp
- Should work, same behaviour w/correct routing handling, if not please report

#2 patched for ipv6, --proto udp6
- #2.a: ipv4 routes: won't be redirected (not even read or written), as the endpoint datagram protocol (ipv6) is different from the tunneled one (ipv4), thus it's kinda N/A touching ipv4 routing given that it doesn't interact at all with the datagram traffic.
  You can always play with --up, or even do "at any time", as ipv4 routing is orthogonal to ipv6's.
- #2.b: ipv6 routes: redirecting not supported (yet).

Can you tell me which of these scenarios are you facing (seems like #2.a) ?

Thanks!

**Comment by yegle** [comment]
Yes I'm facing #2.a
#1 works fine here.

Can you explain a little more detailed why it won't be redirected in #2.a ?
Now I can only change the default ipv4 gateway by hand. This works fine and doesn't have any problem on my situation, I just want this to be automatically changed.

And forgive my poor English, seems I cannot explain myself very clearly :-)

**Comment by yegle** [comment]
Hi jjo~
Any progress on this issue?  :-)

**Comment by jjo** [comment]
Sorry I missed this ... will go into it and ping you back, thanks for the reminder :)

**Comment by jjo** [comment]
Could you apply this small diff (patch -p1):
http://cloud.github.com/downloads/jjo/openvpn-ipv6/v0.4.9-prototype-fix-for-supporting-redirect-gateway.patch
, and feedback me ?

**Comment by yegle** [comment]
Hi jjo:
This patch works fine here!Thank you!

log:
Wed Nov 11 18:28:27 2009 ROUTE default_gateway=XXXXXXXX
Wed Nov 11 18:28:27 2009 TUN/TAP device tun0 opened
Wed Nov 11 18:28:27 2009 TUN/TAP TX queue length set to 100
Wed Nov 11 18:28:27 2009 /sbin/ifconfig tun0 10.8.0.6 pointopoint 10.8.0.5 mtu 1500 
Wed Nov 11 18:28:27 2009 /etc/openvpn/up.sh tun0 1500 1542 10.8.0.6 10.8.0.5 init 
Wed Nov 11 18:28:27 2009 ROUTE remote_host protocol differs from tunneled
Wed Nov 11 18:28:27 2009 /sbin/route add -net 0.0.0.0 netmask 128.0.0.0 gw 10.8.0.5 
Wed Nov 11 18:28:27 2009 /sbin/route add -net 128.0.0.0 netmask 128.0.0.0 gw 10.8.0.5 
Wed Nov 11 18:28:27 2009 /sbin/route add -net 10.8.0.1 netmask 255.255.255.255 gw 10.8.0.5 
Wed Nov 11 18:28:27 2009 Initialization Sequence Completed

**Comment by yegle** [comment]
And, can you provide a binary openvpn.exe using this patch? Thank you~

**Comment by jjo** [comment]
ACK, I'll do it in the next ~few days and ping-back here.

**Comment by jjo** [comment]
Uploaded openvpn.exe ( +signed md5mum ) to http://cloud.github.com/downloads/jjo/openvpn-ipv6/openvpn-ipv6-0.4.10.exe.zip

Enjoy ;)

**Comment by yegle** [comment]
WOW~so fast! Thank you!

**Comment by jjo** [comment]
BTW I rebased to rc21, openssl-0.9.8l and rebuilt a win32 binary:
http://cloud.github.com/downloads/jjo/openvpn-ipv6/openvpn.exe-2.1_rc21-ipv6-0.4.10.zip
