### ISSUE TITLE
provide a patched binary installer for windows user

### ISSUE THREAD

**Issue by yegle** [jjo/openvpn-ipv6-legacy21#9]
Hi there~
I tried to build an installer using your patch for windows user but it seems so complicated.
It's really easy using your patch in Linux but hard for most windows users. 

So can you provide a patched installer for windows user?

**Comment by jjo** [comment]
I don't have a full win32 build environment for easily providing a full installer, _but_ I do build 'openvpn.exe' cuts thru a minimal x-compiling mingw32 env.
Will build it, upload it and update this issue.

**Comment by jjo** [comment]
Just uploaded:
http://cloud.github.com/downloads/jjo/openvpn-ipv6/openvpn-ipv6-0.4.9.exe.zip

**Comment by yegle** [comment]
Thank you jjo :-)

**Comment by yegle** [comment]
Hi jjo,
I'm willing to provide an installer with your patch.

http://yegle.net/openvpn-2.1.1-ipv6-install.exe

Hope this can be added to the download list :-)
